# Generated by Django 2.1.4 on 2019-01-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='is_draft',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Deneme'),
            preserve_default=False,
        ),
    ]
